export const weatherConstant = {
  WEATHER_FETCH_INIT: 'WEATHER_FETCH_INIT',
  WEATHER_BATCH_FETCH_SUCCESS: 'WEATHER_BATCH_FETCH_SUCCESS',
  WEATHER_FETCH_SUCCESS: 'WEATHER_FETCH_SUCCESS',
  WEATHER_FETCH_FAILURE: 'WEATHER_FETCH_FAILURE',
  ADD_WEATHER: 'ADD_WEATHER',
  REMOVE_WEATHER: 'REMOVE_WEATHER',
}
